services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/{Controller,Event}'

  App\Event\ExceptionSubscriber:
    tags: ['kernel.event_subscriber']

  App\Controller\:
    resource: '../src/Controller'
    public: true
    tags: ['controller.service_arguments']
